# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Id_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_numbers', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_p', models.CharField(max_length=2)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
    ]
