# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_auto_20180117_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('cityid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('provinceid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceid', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
