# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0003_auto_20180117_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citys',
            new_name='Cities',
        ),
    ]
